
services:
  guild-assistant-dev:
    image: rawjeev/ai-thin-crust:${DOCKER_TAG}
    container_name: ${CONTAINER_NAME}
    volumes:
      - .:/workspace
      - pydeps:/opt/conda
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: bash
    ports:
      - "8888:8888"  # Jupyter Lab port
      - "6006:6006"  # TensorBoard port
      - "7860:7860"  # Gradio port

volumes:
  pydeps: